### ISSUE TITLE
Can u make multi account version ?

### ISSUE THREAD

**Issue by thesunofme** [WackyDawg/Tapswap-Clicker-v2.0#3]
ur code is amazing and work good with me, but only 1 thread can run. can u make it for multiper account version ? like it will get contentID and chr again every time POST request get more than 5 time error. sry my english not good

**Comment by BraveCanister** [comment]
how do I disable the code? I deleted npm node js, tried changing the URL and then deleting the GIT repository, and when I log in to the account the taps keep going up in an unnatural way.

**Comment by WackyDawg** [comment]
@thesunofme use this repo https://github.com/WackyDawg/Tapswap--Bot it supports multi account

**Comment by WackyDawg** [comment]
@BraveCanister message on telegram https://t.me/d4rk5id3_hacker elaborating your issue
