### ISSUE TITLE
EVERYBODY DONT USE, THIS GUY WANNA MINING ON UR PC

### ISSUE THREAD

**Issue by thesunofme** [WackyDawg/Tapswap-Clicker-v2.0#4]

**Comment by WackyDawg** [comment]
Hello,

Thank you for bringing this to my attention. I apologize for any confusion or concern this may have caused.

This repository was initially intended for another project, but it seems that the eazyminer module was inadvertently included. You can simply edit the package.json file to remove the eazyminer module to address this.

Here are the steps to do so:

Open the package.json file in a text editor.
Locate the dependencies section.
Remove the line that includes "eazyminer": "version".
Save the package.json file.
Run npm install to update the dependencies.
Example:

json
Copy code
```
{
  "type": "module",
  "dependencies": {
    "axios": "^1.7.2",
    "chalk": "^5.3.0",
    "cheerio": "^1.0.0-rc.12",
    "cloudscraper": "^4.6.0",
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    ==> "eazyminer": "^0.1.9",
    "express": "^4.19.2",
    "jsdom": "^24.1.0",
    "puppeteer": "^22.10.0",
    "qs": "^6.12.1",
    "random": "^4.1.0"
  }
} 
```
Additionally, please review the code in the repository. You will see that there is no part that initiates a miner on your device. The script was designed to be deployed on a cloud server (RENDER or HEROKU) and not on your PC .to reduce the costs associated with internet and power, especially for users with busy schedules who might forget to click manually.

Again, I apologize for any inconvenience. Please feel free to reach out if you have any further questions or concerns.
